// HTML-based report generation for Evidence Collection

export function generateEvidenceReport(evidence: any[], audits: any[], reviews: any[], batches: any[], organization: string, userEmail: string) {
  const win = window.open();
  if (!win) {
    alert('Please allow popups to generate reports');
    return;
  }
  
  const date = new Date().toLocaleDateString();
  const totalEvidence = evidence.length;
  const totalAudits = audits.length;
  const totalReviews = reviews.length;
  const totalBatches = batches.length;
  
  // Calculate compliance metrics
  const passedAudits = audits.filter(a => a.status === 'passed').length;
  const auditPassRate = totalAudits > 0 ? Math.round((passedAudits / totalAudits) * 100) : 0;
  const completedEvidence = evidence.filter(e => e.status === 'completed').length;
  const evidenceCompletionRate = totalEvidence > 0 ? Math.round((completedEvidence / totalEvidence) * 100) : 0;
  
  let html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Evidence Collection Report - ${organization}</title>
      <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; }
        h1 { color: #1e40af; border-bottom: 2px solid #1e40af; padding-bottom: 10px; }
        h2 { color: #1e40af; margin-top: 30px; }
        .header { margin-bottom: 30px; }
        .summary { background: #f3f4f6; padding: 15px; border-radius: 8px; margin: 20px 0; }
        .summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 10px; }
        .summary-item { padding: 8px; text-align: center; background: white; border-radius: 8px; }
        .summary-label { font-weight: bold; color: #4b5563; }
        .summary-value { font-size: 24px; font-weight: bold; color: #1e40af; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th { background: #1e40af; color: white; padding: 12px; text-align: left; font-weight: 600; }
        td { padding: 10px; border-bottom: 1px solid #ddd; }
        tr:hover { background: #f9fafb; }
        .footer { margin-top: 30px; text-align: center; font-size: 12px; color: #6b7280; padding-top: 20px; border-top: 1px solid #ddd; }
        .print-btn { 
          margin-top: 20px; 
          padding: 10px 20px; 
          background: #1e40af; 
          color: white; 
          border: none; 
          border-radius: 5px; 
          cursor: pointer;
          font-size: 14px;
        }
        .print-btn:hover { background: #1e3a8a; }
        .status-badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; }
        .status-completed { background: #d1fae5; color: #065f46; }
        .status-in-progress { background: #fed7aa; color: #92400e; }
        .status-passed { background: #d1fae5; color: #065f46; }
        .status-failed { background: #fee2e2; color: #991b1b; }
        @media print {
          body { margin: 0; padding: 20px; }
          .no-print { display: none; }
          th { background: #1e40af !important; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
          .summary-item { background: white !important; }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Evidence Collection Report</h1>
        <p><strong>Organization:</strong> ${organization}</p>
        <p><strong>Generated:</strong> ${date}</p>
        <p><strong>Generated by:</strong> ${userEmail}</p>
      </div>
      
      <div class="summary">
        <h3>Summary Statistics</h3>
        <div class="summary-grid">
          <div class="summary-item"><div class="summary-label">Evidence Records</div><div class="summary-value">${totalEvidence}</div><div class="summary-label" style="font-size:12px">${evidenceCompletionRate}% complete</div></div>
          <div class="summary-item"><div class="summary-label">Audits Completed</div><div class="summary-value">${totalAudits}</div><div class="summary-label" style="font-size:12px">${auditPassRate}% pass rate</div></div>
          <div class="summary-item"><div class="summary-label">Management Reviews</div><div class="summary-value">${totalReviews}</div></div>
          <div class="summary-item"><div class="summary-label">Batch Records</div><div class="summary-value">${totalBatches}</div></div>
        </div>
      </div>
      
      <h2>Evidence Records</h2>
      <table>
        <thead>
          <tr><th>Title</th><th>Reference</th><th>Type</th><th>Created Date</th><th>Created By</th><th>Status</th></tr>
        </thead>
        <tbody>
  `;
  
  evidence.forEach(item => {
    html += `
      <tr>
        <td>${item.title || '-'}</td>
        <td>${item.reference_number || '-'}</td>
        <td>${item.record_type || '-'}</td>
        <td>${item.created_date || '-'}</td>
        <td>${item.created_by || '-'}</td>
        <td><span class="status-badge status-${item.status}">${item.status || 'pending'}</span></td>
      </tr>
    `;
  });
  
  html += `
        </tbody>
      </table>
      
      <h2>Audits</h2>
      <table>
        <thead>
          <tr><th>Audit Title</th><th>Auditor</th><th>Date</th><th>Standard</th><th>Status</th><th>Score</th></tr>
        </thead>
        <tbody>
  `;
  
  audits.forEach(audit => {
    html += `
      <tr>
        <td>${audit.audit_title || '-'}</td>
        <td>${audit.auditor_name || '-'}</td>
        <td>${audit.audit_date || '-'}</td>
        <td>${audit.department_audited || '-'}</td>
        <td><span class="status-badge status-${audit.status}">${audit.status || '-'}</span></td>
        <td>${audit.score || '-'}%</td>
      </tr>
    `;
  });
  
  html += `
        </tbody>
      </table>
      
      <h2>ISO 9001 Compliance Status</h2>
      <div class="summary">
        <div class="summary-grid">
          <div class="summary-item"><div class="summary-label">Evidence Ready</div><div class="summary-value">${Math.round((totalEvidence / 27) * 100)}%</div></div>
          <div class="summary-item"><div class="summary-label">Audit Ready</div><div class="summary-value">${Math.round((totalAudits / 5) * 100)}%</div></div>
          <div class="summary-item"><div class="summary-label">Overall Readiness</div><div class="summary-value">${Math.round(((totalEvidence + totalAudits) / 32) * 100)}%</div></div>
        </div>
      </div>
      
      <div class="footer no-print">
        <button class="print-btn" onclick="window.print()">🖨️ Print / Save as PDF</button>
        <p>Generated by CyberSecureIMS - Cybersecurity Management Platform</p>
      </div>
    </body>
    </html>
  `;
  
  win.document.write(html);
  win.document.close();
}
