// HTML-based report generation for HR module
export function generateHREmployeeReport(employees: any[], organization: string, userEmail: string) {
  const win = window.open();
  if (!win) {
    alert('Please allow popups to generate reports');
    return;
  }
  
  const date = new Date().toLocaleDateString();
  const activeEmployees = employees.filter(e => e.active).length;
  const inductionCompliance = employees.length > 0 
    ? Math.round(employees.filter(e => e.induction_completed).length / employees.length * 100) : 0;
  const competencyRate = employees.length > 0 
    ? Math.round(employees.filter(e => e.competency_verified).length / employees.length * 100) : 0;
  const contractRate = employees.length > 0 
    ? Math.round(employees.filter(e => e.contract_signed).length / employees.length * 100) : 0;
  
  let html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Employee Records Report - ${organization}</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        h1 { color: #1e40af; border-bottom: 2px solid #1e40af; padding-bottom: 10px; }
        .header { margin-bottom: 30px; }
        .summary { background: #f3f4f6; padding: 15px; border-radius: 8px; margin: 20px 0; }
        .summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 10px; }
        .summary-item { padding: 8px; }
        .summary-label { font-weight: bold; color: #4b5563; }
        .summary-value { font-size: 18px; font-weight: bold; color: #1e40af; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th { background: #1e40af; color: white; padding: 12px; text-align: left; font-weight: 600; }
        td { padding: 10px; border-bottom: 1px solid #ddd; }
        tr:hover { background: #f9fafb; }
        .footer { margin-top: 30px; text-align: center; font-size: 12px; color: #6b7280; padding-top: 20px; border-top: 1px solid #ddd; }
        .status-active { color: #10b981; font-weight: bold; }
        .status-inactive { color: #ef4444; font-weight: bold; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; }
        .badge-success { background: #d1fae5; color: #065f46; }
        .badge-warning { background: #fed7aa; color: #92400e; }
        @media print {
          body { margin: 0; padding: 20px; }
          .no-print { display: none; }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Employee Records Report</h1>
        <p><strong>Organization:</strong> ${organization}</p>
        <p><strong>Generated:</strong> ${date}</p>
        <p><strong>Generated by:</strong> ${userEmail}</p>
      </div>
      
      <div class="summary">
        <h3>Summary Statistics</h3>
        <div class="summary-grid">
          <div class="summary-item"><div class="summary-label">Total Employees</div><div class="summary-value">${employees.length}</div></div>
          <div class="summary-item"><div class="summary-label">Active Employees</div><div class="summary-value">${activeEmployees}</div></div>
          <div class="summary-item"><div class="summary-label">Induction Compliance</div><div class="summary-value">${inductionCompliance}%</div></div>
          <div class="summary-item"><div class="summary-label">Competency Rate</div><div class="summary-value">${competencyRate}%</div></div>
          <div class="summary-item"><div class="summary-label">Contract Rate</div><div class="summary-value">${contractRate}%</div></div>
        </div>
      </div>
      
      <table>
        <thead>
          <tr><th>Employee #</th><th>Full Name</th><th>Department</th><th>Position</th><th>Employment Type</th><th>Start Date</th><th>Induction</th><th>Competency</th><th>Contract</th><th>Status</th></tr>
        </thead>
        <tbody>
  `;
  
  employees.forEach(emp => {
    html += `
      <tr>
        <td>${emp.employee_number || '-'}</td>
        <td>${emp.full_name || '-'}</td>
        <td>${emp.department || '-'}</td>
        <td>${emp.position || '-'}</td>
        <td>${emp.employment_type?.replace('_', ' ') || '-'}</td>
        <td>${emp.start_date || '-'}</td>
        <td>${emp.induction_completed ? '✓' : '✗'}</td>
        <td>${emp.competency_verified ? '✓' : '✗'}</td>
        <td>${emp.contract_signed ? '✓' : '✗'}</td>
        <td class="${emp.active ? 'status-active' : 'status-inactive'}">${emp.active ? 'Active' : 'Inactive'}</td>
      </tr>
    `;
  });
  
  html += `
        </tbody>
       </table>
      <div class="footer no-print">
        <button onclick="window.print()" style="padding: 10px 20px; background: #1e40af; color: white; border: none; border-radius: 5px; cursor: pointer;">
          🖨️ Print / Save as PDF
        </button>
        <p>Generated by CyberSecureIMS - Cybersecurity Management Platform</p>
      </div>
    </body>
    </html>
  `;
  
  win.document.write(html);
  win.document.close();
}

export function generateHRTaskReport(tasks: any[], organization: string, userEmail: string) {
  const win = window.open();
  if (!win) {
    alert('Please allow popups to generate reports');
    return;
  }
  
  const date = new Date().toLocaleDateString();
  const pendingTasks = tasks.filter(t => t.status === 'pending').length;
  const inProgressTasks = tasks.filter(t => t.status === 'in_progress').length;
  const completedTasks = tasks.filter(t => t.status === 'completed').length;
  
  let html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>HR Tasks Report - ${organization}</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        h1 { color: #1e40af; border-bottom: 2px solid #1e40af; padding-bottom: 10px; }
        .header { margin-bottom: 30px; }
        .summary { background: #f3f4f6; padding: 15px; border-radius: 8px; margin: 20px 0; }
        .summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 10px; }
        .summary-item { padding: 8px; text-align: center; }
        .summary-label { font-weight: bold; color: #4b5563; }
        .summary-value { font-size: 24px; font-weight: bold; }
        .summary-pending { color: #f59e0b; }
        .summary-progress { color: #3b82f6; }
        .summary-completed { color: #10b981; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th { background: #1e40af; color: white; padding: 12px; text-align: left; }
        td { padding: 10px; border-bottom: 1px solid #ddd; }
        tr:hover { background: #f9fafb; }
        .footer { margin-top: 30px; text-align: center; font-size: 12px; color: #6b7280; padding-top: 20px; border-top: 1px solid #ddd; }
        .priority-high { color: #ef4444; font-weight: bold; }
        .priority-medium { color: #f59e0b; }
        .priority-low { color: #10b981; }
        @media print {
          body { margin: 0; padding: 20px; }
          .no-print { display: none; }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>HR Tasks Report</h1>
        <p><strong>Organization:</strong> ${organization}</p>
        <p><strong>Generated:</strong> ${date}</p>
        <p><strong>Generated by:</strong> ${userEmail}</p>
      </div>
      
      <div class="summary">
        <h3>Task Summary</h3>
        <div class="summary-grid">
          <div class="summary-item"><div class="summary-label">Pending</div><div class="summary-value summary-pending">${pendingTasks}</div></div>
          <div class="summary-item"><div class="summary-label">In Progress</div><div class="summary-value summary-progress">${inProgressTasks}</div></div>
          <div class="summary-item"><div class="summary-label">Completed</div><div class="summary-value summary-completed">${completedTasks}</div></div>
          <div class="summary-item"><div class="summary-label">Total Tasks</div><div class="summary-value">${tasks.length}</div></div>
        </div>
      </div>
      
      <table>
        <thead>
          <tr><th>Title</th><th>Category</th><th>Priority</th><th>Status</th><th>Assigned To</th><th>Due Date</th></tr>
        </thead>
        <tbody>
  `;
  
  tasks.forEach(task => {
    const priorityClass = task.priority === 'high' ? 'priority-high' : task.priority === 'medium' ? 'priority-medium' : 'priority-low';
    html += `
      <tr>
        <td>${task.title || '-'}</td>
        <td>${task.category || '-'}</td>
        <td class="${priorityClass}">${task.priority?.toUpperCase() || '-'}</td>
        <td>${task.status?.replace('_', ' ') || '-'}</td>
        <td>${task.assigned_to || '-'}</td>
        <td>${task.due_date || 'N/A'}</td>
      </tr>
    `;
  });
  
  html += `
        </tbody>
       </table>
      <div class="footer no-print">
        <button onclick="window.print()" style="padding: 10px 20px; background: #1e40af; color: white; border: none; border-radius: 5px; cursor: pointer;">
          🖨️ Print / Save as PDF
        </button>
        <p>Generated by CyberSecureIMS - Cybersecurity Management Platform</p>
      </div>
    </body>
    </html>
  `;
  
  win.document.write(html);
  win.document.close();
}
