import PageHeader from '@/components/PageHeader';
import { AlertTriangle } from 'lucide-react';
import React, { useState } from 'react';
import { supabase } from '../lib/supabase';
import { useAuth } from '../contexts/AuthContext';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

export default function RiskAssessment() {
  const { profile } = useAuth();
  const organizationId = profile?.organization_id;
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null);

  const [form, setForm] = useState({
    risk_title: '',
    risk_description: '',
    likelihood: 1,
    impact: 1,
    status: 'Open'
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!organizationId) {
      setMessage({ type: 'error', text: 'Organization not loaded' });
      return;
    }

    setLoading(true);
    setMessage(null);

    try {
      const { error } = await supabase
        .from('cyber_risks')
        .insert({
          organization_id: organizationId,
          risk_title: form.risk_title,
          risk_description: form.risk_description,
          likelihood: form.likelihood,
          impact: form.impact,
          status: form.status
          // DO NOT send risk_score → it is generated by the database
        });

      if (error) throw error;

      setMessage({ type: 'success', text: 'Risk added successfully!' });
      setForm({ risk_title: '', risk_description: '', likelihood: 1, impact: 1, status: 'Open' });
    } catch (err: any) {
      console.error(err);
      setMessage({ type: 'error', text: err.message || 'Failed to save risk' });
    } finally {
      setLoading(false);
    }
  };

  return (
    <Card className="max-w-2xl mx-auto mt-8">
      <CardHeader>
        <CardTitle>Add New Risk</CardTitle>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <Label>Risk Title</Label>
            <Input
              value={form.risk_title}
              onChange={(e) => setForm({ ...form, risk_title: e.target.value })}
              required
            />
          </div>

          <div>
            <Label>Description</Label>
            <Textarea
              value={form.risk_description}
              onChange={(e) => setForm({ ...form, risk_description: e.target.value })}
              required
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <Label>Likelihood (1-5)</Label>
              <Select value={String(form.likelihood)} onValueChange={(v) => setForm({ ...form, likelihood: Number(v) })}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {[1,2,3,4,5].map(n => <SelectItem key={n} value={String(n)}>{n}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>

            <div>
              <Label>Impact (1-5)</Label>
              <Select value={String(form.impact)} onValueChange={(v) => setForm({ ...form, impact: Number(v) })}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {[1,2,3,4,5].map(n => <SelectItem key={n} value={String(n)}>{n}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
          </div>

          <Button type="submit" disabled={loading} className="w-full">
            {loading ? 'Saving...' : 'Save Risk'}
          </Button>

          {message && (
            <p className={message.type === 'success' ? 'text-green-600' : 'text-red-600'}>
              {message.text}
            </p>
          )}
        </form>
      </CardContent>
    </Card>
  );
}
