-- ============================================================
-- CyberSecureIMS - Seed Framework Controls
-- Phase 2 / Phase 6: Pre-seed ISO 27001, SOC 2, NIST CSF controls
-- Called by: edge function OR run manually per org
-- Replace :org_id with the actual organization UUID
-- ============================================================

-- ============================================================
-- ISO 27001:2022 - All 93 Controls (Annex A)
-- ============================================================
INSERT INTO framework_controls (organization_id, framework, control_id, control_domain, control_title, control_description, control_type, status)
SELECT
  :org_id,
  'ISO27001',
  c.control_id,
  c.domain,
  c.title,
  c.description,
  c.type,
  'not_started'
FROM (VALUES
  -- A.5 Organizational Controls
  ('A.5.1',  'A.5 Organizational Controls', 'Policies for information security',
   'Information security policy and topic-specific policies shall be defined, approved, communicated and acknowledged.', 'preventive'),
  ('A.5.2',  'A.5 Organizational Controls', 'Information security roles and responsibilities',
   'Information security roles and responsibilities shall be defined and allocated.', 'preventive'),
  ('A.5.3',  'A.5 Organizational Controls', 'Segregation of duties',
   'Conflicting duties and conflicting areas of responsibility shall be segregated.', 'preventive'),
  ('A.5.4',  'A.5 Organizational Controls', 'Management responsibilities',
   'Management shall require all personnel to apply information security per established policies.', 'preventive'),
  ('A.5.5',  'A.5 Organizational Controls', 'Contact with authorities',
   'The organization shall establish and maintain contact with relevant authorities.', 'detective'),
  ('A.5.6',  'A.5 Organizational Controls', 'Contact with special interest groups',
   'The organization shall establish and maintain contact with special interest groups.', 'detective'),
  ('A.5.7',  'A.5 Organizational Controls', 'Threat intelligence',
   'Information relating to information security threats shall be collected and analysed.', 'detective'),
  ('A.5.8',  'A.5 Organizational Controls', 'Information security in project management',
   'Information security shall be integrated into project management.', 'preventive'),
  ('A.5.9',  'A.5 Organizational Controls', 'Inventory of information and other associated assets',
   'An inventory of information and associated assets shall be developed and maintained.', 'preventive'),
  ('A.5.10', 'A.5 Organizational Controls', 'Acceptable use of information and other associated assets',
   'Rules for acceptable use and handling of information and assets shall be identified, documented and implemented.', 'preventive'),
  ('A.5.11', 'A.5 Organizational Controls', 'Return of assets',
   'Personnel and other interested parties shall return all assets upon change or termination of employment.', 'preventive'),
  ('A.5.12', 'A.5 Organizational Controls', 'Classification of information',
   'Information shall be classified according to confidentiality, integrity and availability.', 'preventive'),
  ('A.5.13', 'A.5 Organizational Controls', 'Labelling of information',
   'An appropriate set of procedures for information labelling shall be developed and implemented.', 'preventive'),
  ('A.5.14', 'A.5 Organizational Controls', 'Information transfer',
   'Information transfer rules, procedures, or agreements shall be in place.', 'preventive'),
  ('A.5.15', 'A.5 Organizational Controls', 'Access control',
   'Rules to control physical and logical access to information and associated assets shall be established and implemented.', 'preventive'),
  ('A.5.16', 'A.5 Organizational Controls', 'Identity management',
   'The full lifecycle of identities shall be managed.', 'preventive'),
  ('A.5.17', 'A.5 Organizational Controls', 'Authentication information',
   'Allocation and management of authentication information shall be controlled.', 'preventive'),
  ('A.5.18', 'A.5 Organizational Controls', 'Access rights',
   'Access rights to information and other associated assets shall be provisioned, reviewed, modified and removed.', 'preventive'),
  ('A.5.19', 'A.5 Organizational Controls', 'Information security in supplier relationships',
   'Processes and procedures to manage information security risk in supplier relationships shall be defined and implemented.', 'preventive'),
  ('A.5.20', 'A.5 Organizational Controls', 'Addressing information security within supplier agreements',
   'Relevant information security requirements shall be established and agreed with each supplier.', 'preventive'),
  ('A.5.21', 'A.5 Organizational Controls', 'Managing information security in the ICT supply chain',
   'Processes and procedures shall be defined and implemented to manage the information security risks associated with the ICT supply chain.', 'preventive'),
  ('A.5.22', 'A.5 Organizational Controls', 'Monitoring, review and change management of supplier services',
   'The organization shall regularly monitor, review, evaluate and manage change in supplier information security practices.', 'detective'),
  ('A.5.23', 'A.5 Organizational Controls', 'Information security for use of cloud services',
   'Processes for acquisition, use, management and exit from cloud services shall be established.', 'preventive'),
  ('A.5.24', 'A.5 Organizational Controls', 'Information security incident management planning and preparation',
   'The organization shall plan and prepare for managing information security incidents by defining processes and procedures.', 'corrective'),
  ('A.5.25', 'A.5 Organizational Controls', 'Assessment and decision on information security events',
   'The organization shall assess information security events and decide if they are to be categorized as incidents.', 'detective'),
  ('A.5.26', 'A.5 Organizational Controls', 'Response to information security incidents',
   'Information security incidents shall be responded to in accordance with documented procedures.', 'corrective'),
  ('A.5.27', 'A.5 Organizational Controls', 'Learning from information security incidents',
   'Knowledge gained from information security incidents shall be used to strengthen and improve the controls.', 'corrective'),
  ('A.5.28', 'A.5 Organizational Controls', 'Collection of evidence',
   'The organization shall establish and implement procedures for the identification, collection, acquisition and preservation of evidence related to information security events.', 'detective'),
  ('A.5.29', 'A.5 Organizational Controls', 'Information security during disruption',
   'The organization shall plan how to maintain information security at an appropriate level during disruption.', 'corrective'),
  ('A.5.30', 'A.5 Organizational Controls', 'ICT readiness for business continuity',
   'ICT readiness shall be planned, implemented, maintained and tested based on business continuity objectives.', 'preventive'),
  ('A.5.31', 'A.5 Organizational Controls', 'Legal, statutory, regulatory and contractual requirements',
   'Legal, statutory, regulatory and contractual requirements relevant to information security shall be identified, documented and kept up to date.', 'preventive'),
  ('A.5.32', 'A.5 Organizational Controls', 'Intellectual property rights',
   'The organization shall implement appropriate procedures to protect intellectual property rights.', 'preventive'),
  ('A.5.33', 'A.5 Organizational Controls', 'Protection of records',
   'Records shall be protected from loss, destruction, falsification, unauthorized access and unauthorized release.', 'preventive'),
  ('A.5.34', 'A.5 Organizational Controls', 'Privacy and protection of personal information (PII)',
   'The organization shall identify and meet the requirements regarding the preservation of privacy and protection of PII.', 'preventive'),
  ('A.5.35', 'A.5 Organizational Controls', 'Independent review of information security',
   'The approach to managing information security and its implementation shall be reviewed independently at planned intervals.', 'detective'),
  ('A.5.36', 'A.5 Organizational Controls', 'Compliance with policies, rules and standards for information security',
   'Compliance with the policies, topic-specific policies, rules and standards shall be regularly reviewed.', 'detective'),
  ('A.5.37', 'A.5 Organizational Controls', 'Documented operating procedures',
   'Operating procedures for information processing facilities shall be documented and made available to personnel who need them.', 'preventive'),
  -- A.6 People Controls
  ('A.6.1',  'A.6 People Controls', 'Screening',
   'Background verification checks shall be carried out on all candidates for employment.', 'preventive'),
  ('A.6.2',  'A.6 People Controls', 'Terms and conditions of employment',
   'Employment contracts shall state the responsibilities of personnel and the organization for information security.', 'preventive'),
  ('A.6.3',  'A.6 People Controls', 'Information security awareness, education and training',
   'Personnel and relevant interested parties shall receive appropriate training and awareness updates.', 'preventive'),
  ('A.6.4',  'A.6 People Controls', 'Disciplinary process',
   'A disciplinary process shall be formalized and communicated to take actions against personnel who have committed an information security policy violation.', 'corrective'),
  ('A.6.5',  'A.6 People Controls', 'Responsibilities after termination or change of employment',
   'Information security responsibilities and duties that remain valid after termination or change of employment shall be defined, enforced and communicated.', 'preventive'),
  ('A.6.6',  'A.6 People Controls', 'Confidentiality or non-disclosure agreements',
   'Confidentiality or non-disclosure agreements reflecting the organization needs for protection of information shall be identified, documented, regularly reviewed and signed.', 'preventive'),
  ('A.6.7',  'A.6 People Controls', 'Remote working',
   'Security measures shall be implemented when personnel are working remotely to protect information accessed, processed or stored outside the organization premises.', 'preventive'),
  ('A.6.8',  'A.6 People Controls', 'Information security event reporting',
   'The organization shall provide a mechanism for personnel to report observed or suspected information security events in a timely manner.', 'detective'),
  -- A.7 Physical Controls
  ('A.7.1',  'A.7 Physical Controls', 'Physical security perimeters',
   'Security perimeters shall be defined and used to protect areas that contain information and other associated assets.', 'preventive'),
  ('A.7.2',  'A.7 Physical Controls', 'Physical entry',
   'Secure areas shall be protected by appropriate entry controls and access points.', 'preventive'),
  ('A.7.3',  'A.7 Physical Controls', 'Securing offices, rooms and facilities',
   'Physical security for offices, rooms and facilities shall be designed and implemented.', 'preventive'),
  ('A.7.4',  'A.7 Physical Controls', 'Physical security monitoring',
   'Premises shall be continuously monitored for unauthorized physical access.', 'detective'),
  ('A.7.5',  'A.7 Physical Controls', 'Protecting against physical and environmental threats',
   'Protection against physical and environmental threats shall be designed and implemented.', 'preventive'),
  ('A.7.6',  'A.7 Physical Controls', 'Working in secure areas',
   'Security measures for working in secure areas shall be designed and implemented.', 'preventive'),
  ('A.7.7',  'A.7 Physical Controls', 'Clear desk and clear screen',
   'Clear desk rules for papers and removable storage media and clear screen rules for information processing facilities shall be defined and implemented.', 'preventive'),
  ('A.7.8',  'A.7 Physical Controls', 'Equipment siting and protection',
   'Equipment shall be sited securely and protected.', 'preventive'),
  ('A.7.9',  'A.7 Physical Controls', 'Security of assets off-premises',
   'Off-site assets shall be protected.', 'preventive'),
  ('A.7.10', 'A.7 Physical Controls', 'Storage media',
   'Storage media shall be managed through their lifecycle of acquisition, use, transportation and disposal.', 'preventive'),
  ('A.7.11', 'A.7 Physical Controls', 'Supporting utilities',
   'Information processing facilities shall be protected from power failures and other disruptions.', 'preventive'),
  ('A.7.12', 'A.7 Physical Controls', 'Cabling security',
   'Cables carrying power, data or supporting information services shall be protected from interception, interference or damage.', 'preventive'),
  ('A.7.13', 'A.7 Physical Controls', 'Equipment maintenance',
   'Equipment shall be maintained correctly to ensure availability, integrity and confidentiality of information.', 'preventive'),
  ('A.7.14', 'A.7 Physical Controls', 'Secure disposal or re-use of equipment',
   'Items of equipment containing storage media shall be verified to ensure that any sensitive data and licensed software has been removed prior to disposal.', 'preventive'),
  -- A.8 Technological Controls
  ('A.8.1',  'A.8 Technological Controls', 'User endpoint devices',
   'Information stored on, processed by or accessible via user endpoint devices shall be protected.', 'preventive'),
  ('A.8.2',  'A.8 Technological Controls', 'Privileged access rights',
   'The allocation and use of privileged access rights shall be restricted and managed.', 'preventive'),
  ('A.8.3',  'A.8 Technological Controls', 'Information access restriction',
   'Access to information and other associated assets shall be restricted in accordance with the access control policy.', 'preventive'),
  ('A.8.4',  'A.8 Technological Controls', 'Access to source code',
   'Read and write access to source code, development tools and software libraries shall be appropriately managed.', 'preventive'),
  ('A.8.5',  'A.8 Technological Controls', 'Secure authentication',
   'Secure authentication technologies and procedures shall be implemented based on information access restrictions and the topic-specific policy on access control.', 'preventive'),
  ('A.8.6',  'A.8 Technological Controls', 'Capacity management',
   'The use of resources shall be monitored and adjusted to meet current and expected capacity requirements.', 'preventive'),
  ('A.8.7',  'A.8 Technological Controls', 'Protection against malware',
   'Protection against malware shall be implemented and supported by appropriate user awareness.', 'preventive'),
  ('A.8.8',  'A.8 Technological Controls', 'Management of technical vulnerabilities',
   'Information about technical vulnerabilities of information systems in use shall be obtained in a timely fashion.', 'detective'),
  ('A.8.9',  'A.8 Technological Controls', 'Configuration management',
   'Configurations of hardware, software, services and networks shall be established, documented, implemented, monitored and reviewed.', 'preventive'),
  ('A.8.10', 'A.8 Technological Controls', 'Information deletion',
   'Information stored in information systems, devices or in any other storage media shall be deleted when no longer required.', 'preventive'),
  ('A.8.11', 'A.8 Technological Controls', 'Data masking',
   'Data masking shall be used in accordance with the organization topic-specific policy on access control and other related policies.', 'preventive'),
  ('A.8.12', 'A.8 Technological Controls', 'Data leakage prevention',
   'Data leakage prevention measures shall be applied to systems, networks and any other devices that process, store or transmit sensitive information.', 'preventive'),
  ('A.8.13', 'A.8 Technological Controls', 'Information backup',
   'Backup copies of information, software and systems shall be maintained and regularly tested.', 'corrective'),
  ('A.8.14', 'A.8 Technological Controls', 'Redundancy of information processing facilities',
   'Information processing facilities shall be implemented with redundancy sufficient to meet availability requirements.', 'preventive'),
  ('A.8.15', 'A.8 Technological Controls', 'Logging',
   'Logs that record activities, exceptions, faults and other relevant events shall be produced, stored, protected and analysed.', 'detective'),
  ('A.8.16', 'A.8 Technological Controls', 'Monitoring activities',
   'Networks, systems and applications shall be monitored for anomalous behaviour.', 'detective'),
  ('A.8.17', 'A.8 Technological Controls', 'Clock synchronization',
   'The clocks of information processing systems used by the organization shall be synchronized.', 'preventive'),
  ('A.8.18', 'A.8 Technological Controls', 'Use of privileged utility programs',
   'The use of utility programs that might be capable of overriding system and application controls shall be restricted.', 'preventive'),
  ('A.8.19', 'A.8 Technological Controls', 'Installation of software on operational systems',
   'Procedures and measures shall be implemented to securely manage software installation on operational systems.', 'preventive'),
  ('A.8.20', 'A.8 Technological Controls', 'Networks security',
   'Networks and network devices shall be secured, managed and controlled to protect information in systems and applications.', 'preventive'),
  ('A.8.21', 'A.8 Technological Controls', 'Security of network services',
   'Security mechanisms, service levels and requirements of network services shall be identified, implemented and monitored.', 'preventive'),
  ('A.8.22', 'A.8 Technological Controls', 'Segregation of networks',
   'Groups of information services, users and information systems shall be segregated in the organization networks.', 'preventive'),
  ('A.8.23', 'A.8 Technological Controls', 'Web filtering',
   'Access to external websites shall be managed to reduce exposure to malicious content.', 'preventive'),
  ('A.8.24', 'A.8 Technological Controls', 'Use of cryptography',
   'Rules for the effective use of cryptography shall be defined and implemented.', 'preventive'),
  ('A.8.25', 'A.8 Technological Controls', 'Secure development life cycle',
   'Rules for the secure development of software and systems shall be established and applied.', 'preventive'),
  ('A.8.26', 'A.8 Technological Controls', 'Application security requirements',
   'Information security requirements shall be identified, specified and approved when developing or acquiring applications.', 'preventive'),
  ('A.8.27', 'A.8 Technological Controls', 'Secure system architecture and engineering principles',
   'Principles for engineering secure systems shall be established, documented, maintained and applied.', 'preventive'),
  ('A.8.28', 'A.8 Technological Controls', 'Secure coding',
   'Secure coding principles shall be applied to software development.', 'preventive'),
  ('A.8.29', 'A.8 Technological Controls', 'Security testing in development and acceptance',
   'Security testing processes shall be defined and implemented in the development life cycle.', 'detective'),
  ('A.8.30', 'A.8 Technological Controls', 'Outsourced development',
   'The organization shall direct, monitor and review the activities related to outsourced system development.', 'preventive'),
  ('A.8.31', 'A.8 Technological Controls', 'Separation of development, test and production environments',
   'Development, testing and production environments shall be separated and secured.', 'preventive'),
  ('A.8.32', 'A.8 Technological Controls', 'Change management',
   'Changes to information processing facilities and information systems shall be subject to change management procedures.', 'preventive'),
  ('A.8.33', 'A.8 Technological Controls', 'Test information',
   'Test information shall be appropriately selected, protected and managed.', 'preventive'),
  ('A.8.34', 'A.8 Technological Controls', 'Protection of information systems during audit testing',
   'Audit tests and other assurance activities involving assessment of operational systems shall be planned and agreed between the tester and appropriate management.', 'preventive')
) AS c(control_id, domain, title, description, type)
ON CONFLICT (organization_id, framework, control_id) DO NOTHING;

-- ============================================================
-- SOC 2 Trust Service Criteria (TSC)
-- ============================================================
INSERT INTO framework_controls (organization_id, framework, control_id, control_domain, control_title, control_description, control_type, status)
SELECT
  :org_id, 'SOC2', c.control_id, c.domain, c.title, c.description, c.type, 'not_started'
FROM (VALUES
  -- CC1 – Control Environment
  ('CC1.1', 'CC1 Control Environment', 'Board Oversight', 'COSO Principle 1: The entity demonstrates a commitment to integrity and ethical values.', 'preventive'),
  ('CC1.2', 'CC1 Control Environment', 'Board Independence', 'COSO Principle 2: The board of directors demonstrates independence from management.', 'preventive'),
  ('CC1.3', 'CC1 Control Environment', 'Organizational Structure', 'COSO Principle 3: Management establishes structures, reporting lines and appropriate authorities.', 'preventive'),
  ('CC1.4', 'CC1 Control Environment', 'Commitment to Competence', 'COSO Principle 4: The entity demonstrates a commitment to attract, develop and retain competent individuals.', 'preventive'),
  ('CC1.5', 'CC1 Control Environment', 'Enforcement of Accountability', 'COSO Principle 5: The entity holds individuals accountable for their responsibilities.', 'detective'),
  -- CC2 – Communication & Information
  ('CC2.1', 'CC2 Communication & Information', 'Internal Communication', 'The entity obtains or generates and uses relevant quality information to support the functioning of internal control.', 'preventive'),
  ('CC2.2', 'CC2 Communication & Information', 'External Communication', 'The entity communicates externally to allow stakeholders to understand commitments and obligations.', 'preventive'),
  ('CC2.3', 'CC2 Communication & Information', 'Communication to Relevant Parties', 'The entity communicates with external parties regarding matters affecting the functioning of internal control.', 'preventive'),
  -- CC3 – Risk Assessment
  ('CC3.1', 'CC3 Risk Assessment', 'Risk Identification', 'The entity specifies objectives with sufficient clarity to enable identification of risks.', 'preventive'),
  ('CC3.2', 'CC3 Risk Assessment', 'Risk Analysis', 'The entity identifies risks to the achievement of its objectives across the entity.', 'detective'),
  ('CC3.3', 'CC3 Risk Assessment', 'Fraud Risk', 'The entity considers the potential for fraud in assessing risks to the achievement of objectives.', 'detective'),
  ('CC3.4', 'CC3 Risk Assessment', 'Change Risk', 'The entity identifies and assesses changes that could significantly impact the system of internal control.', 'detective'),
  -- CC4 – Monitoring
  ('CC4.1', 'CC4 Monitoring', 'Ongoing Monitoring', 'The entity selects, develops and performs ongoing and/or separate evaluations to ascertain whether components of internal control are present and functioning.', 'detective'),
  ('CC4.2', 'CC4 Monitoring', 'Evaluation & Communication of Deficiencies', 'The entity evaluates and communicates internal control deficiencies in a timely manner.', 'detective'),
  -- CC5 – Control Activities
  ('CC5.1', 'CC5 Control Activities', 'Control Selection and Development', 'The entity selects and develops control activities that contribute to the mitigation of risks.', 'preventive'),
  ('CC5.2', 'CC5 Control Activities', 'Technology Controls', 'The entity selects and develops general control activities over technology to support the achievement of objectives.', 'preventive'),
  ('CC5.3', 'CC5 Control Activities', 'Policy Deployment', 'The entity deploys control activities through policies that establish what is expected and procedures that put policies into action.', 'preventive'),
  -- CC6 – Logical & Physical Access
  ('CC6.1', 'CC6 Logical & Physical Access', 'Logical Access Security Software', 'The entity implements logical access security software, infrastructure and architectures.', 'preventive'),
  ('CC6.2', 'CC6 Logical & Physical Access', 'Authentication', 'Prior to issuing system credentials, the entity registers and authorizes new internal and external users.', 'preventive'),
  ('CC6.3', 'CC6 Logical & Physical Access', 'Role-Based Access', 'The entity authorizes, modifies or removes access to data, software, functions and other protected assets.', 'preventive'),
  ('CC6.4', 'CC6 Logical & Physical Access', 'Physical Access Restriction', 'The entity restricts physical access to facilities and protected information assets to authorized personnel.', 'preventive'),
  ('CC6.5', 'CC6 Logical & Physical Access', 'Logical Access Termination', 'The entity discontinues logical and physical protections for terminated users.', 'preventive'),
  ('CC6.6', 'CC6 Logical & Physical Access', 'External Threat Protection', 'The entity implements controls to prevent or detect and act upon the introduction of unauthorized or malicious software.', 'detective'),
  ('CC6.7', 'CC6 Logical & Physical Access', 'Data Transmission Controls', 'The entity restricts the transmission, movement and removal of information to authorized internal and external users.', 'preventive'),
  ('CC6.8', 'CC6 Logical & Physical Access', 'Malware Prevention', 'The entity implements controls to prevent or detect and act upon the introduction of unauthorized or malicious software.', 'preventive'),
  -- CC7 – System Operations
  ('CC7.1', 'CC7 System Operations', 'Vulnerability Management', 'The entity uses detection and monitoring procedures to identify changes to configurations and new vulnerabilities.', 'detective'),
  ('CC7.2', 'CC7 System Operations', 'Anomaly Monitoring', 'The entity monitors system components and the operation of those components for anomalies.', 'detective'),
  ('CC7.3', 'CC7 System Operations', 'Incident Evaluation', 'The entity evaluates security events to determine whether they could or have resulted in a failure of the entity to meet its objectives.', 'detective'),
  ('CC7.4', 'CC7 System Operations', 'Incident Response', 'The entity responds to identified security incidents by executing a defined incident-response program.', 'corrective'),
  ('CC7.5', 'CC7 System Operations', 'Incident Recovery', 'The entity identifies, develops and implements activities to recover from identified security incidents.', 'corrective'),
  -- CC8 – Change Management
  ('CC8.1', 'CC8 Change Management', 'Change Management Process', 'The entity authorizes, designs, develops or acquires, configures, documents, tests, approves and implements changes.', 'preventive'),
  -- CC9 – Risk Mitigation
  ('CC9.1', 'CC9 Risk Mitigation', 'Risk Mitigation Activities', 'The entity identifies, selects and develops risk mitigation activities for identified risks.', 'preventive'),
  ('CC9.2', 'CC9 Risk Mitigation', 'Vendor Risk Management', 'The entity assesses and manages risks associated with vendors and business partners.', 'preventive'),
  -- Availability
  ('A1.1',  'Availability', 'Availability Capacity', 'The entity maintains, monitors and evaluates current processing capacity and use of system components.', 'preventive'),
  ('A1.2',  'Availability', 'Environmental Threats', 'The entity authorizes, designs, develops or acquires, implements, operates, approves, maintains and monitors environmental protections.', 'preventive'),
  ('A1.3',  'Availability', 'Recovery Plan', 'The entity tests recovery plan procedures to meet its availability commitments and system requirements.', 'corrective'),
  -- Confidentiality
  ('C1.1',  'Confidentiality', 'Confidential Information Identification', 'The entity identifies and maintains confidential information to meet its objectives.', 'preventive'),
  ('C1.2',  'Confidentiality', 'Confidential Information Disposal', 'The entity disposes of confidential information to meet its objectives.', 'preventive')
) AS c(control_id, domain, title, description, type)
ON CONFLICT (organization_id, framework, control_id) DO NOTHING;

-- ============================================================
-- NIST Cybersecurity Framework 2.0 (CSF)
-- ============================================================
INSERT INTO framework_controls (organization_id, framework, control_id, control_domain, control_title, control_description, control_type, status)
SELECT
  :org_id, 'NIST_CSF', c.control_id, c.domain, c.title, c.description, c.type, 'not_started'
FROM (VALUES
  -- GV – Govern
  ('GV.OC-01', 'GV Govern', 'Organizational Mission', 'The organizational mission is understood and informs cybersecurity risk management decisions.', 'preventive'),
  ('GV.OC-02', 'GV Govern', 'Internal/External Stakeholders', 'Internal and external stakeholders are understood, and their needs are considered in cybersecurity risk management decisions.', 'preventive'),
  ('GV.OC-03', 'GV Govern', 'Legal Requirements', 'Legal, regulatory and contractual requirements regarding cybersecurity – including privacy and civil liberties obligations – are understood and managed.', 'preventive'),
  ('GV.OC-04', 'GV Govern', 'Critical Objectives', 'Critical objectives, capabilities and services that stakeholders depend on or expect from the organization are understood.', 'preventive'),
  ('GV.OC-05', 'GV Govern', 'Outcomes and Dependencies', 'Outcomes, capabilities, and services that the organization depends on are understood.', 'preventive'),
  ('GV.RM-01', 'GV Govern', 'Risk Management Strategy', 'Risk management objectives are established and agreed to by organizational stakeholders.', 'preventive'),
  ('GV.RM-02', 'GV Govern', 'Risk Appetite', 'Risk appetite and risk tolerance statements are established, communicated and maintained.', 'preventive'),
  ('GV.RM-03', 'GV Govern', 'Risk Communication', 'Cybersecurity risk management activities and outcomes are included in enterprise-wide risk management activities.', 'preventive'),
  ('GV.RM-04', 'GV Govern', 'Strategic Direction', 'Strategic direction that describes appropriate risk response options is established and communicated.', 'preventive'),
  ('GV.RM-05', 'GV Govern', 'Risk Roles', 'Lines of communication across the organization are established for cybersecurity risks.', 'preventive'),
  ('GV.RM-06', 'GV Govern', 'Standardized Responses', 'A standardized method for calculating, documenting, categorizing and prioritizing cybersecurity risks is established and communicated.', 'preventive'),
  ('GV.RM-07', 'GV Govern', 'Strategic Opportunities', 'Strategic opportunities that can be realized through appropriate management of cybersecurity risk are characterized and communicated.', 'preventive'),
  ('GV.RR-01', 'GV Govern', 'Leadership Accountability', 'Organizational leadership is responsible and accountable for cybersecurity risk and fosters a culture that is risk-aware, ethical and continually improving.', 'preventive'),
  ('GV.RR-02', 'GV Govern', 'Roles and Responsibilities', 'Roles, responsibilities and authorities related to cybersecurity risk management are established, communicated and enforced.', 'preventive'),
  ('GV.RR-03', 'GV Govern', 'Adequate Resources', 'Adequate resources are allocated commensurate with the cybersecurity risk strategy, roles, responsibilities and policies.', 'preventive'),
  ('GV.RR-04', 'GV Govern', 'Cybersecurity Policies', 'Cybersecurity is included in human resources practices.', 'preventive'),
  ('GV.PO-01', 'GV Govern', 'Policy Establishment', 'Policy for managing cybersecurity risks is established based on organizational context and communicated.', 'preventive'),
  ('GV.PO-02', 'GV Govern', 'Policy Review', 'Policy for managing cybersecurity risks is reviewed, updated, communicated and enforced.', 'preventive'),
  ('GV.OV-01', 'GV Govern', 'Cybersecurity Risk Results', 'Cybersecurity risk management strategy outcomes are reviewed to inform and adjust strategy and direction.', 'detective'),
  ('GV.OV-02', 'GV Govern', 'Performance Review', 'The cybersecurity risk management strategy is reviewed and adjusted to ensure coverage of organizational requirements.', 'detective'),
  ('GV.OV-03', 'GV Govern', 'Organizational Performance', 'Organizational cybersecurity risk management performance is evaluated and reviewed for adjustments needed.', 'detective'),
  ('GV.SC-01', 'GV Govern', 'Supply Chain Risk', 'A cybersecurity supply chain risk management program, strategy, objectives, policies and processes are established and agreed to by organizational stakeholders.', 'preventive'),
  ('GV.SC-02', 'GV Govern', 'Supplier Relationships', 'Cybersecurity roles and responsibilities for suppliers, customers, partners and third-party stakeholders are established, communicated and coordinated.', 'preventive'),
  ('GV.SC-03', 'GV Govern', 'Supply Chain Integration', 'Cybersecurity supply chain risk management is integrated into broader enterprise risk management.', 'preventive'),
  ('GV.SC-04', 'GV Govern', 'Supplier Selection', 'Suppliers are known and prioritized by criticality.', 'preventive'),
  ('GV.SC-05', 'GV Govern', 'Supplier Requirements', 'Requirements to address cybersecurity risks in supply chains are established, prioritized and integrated into contracts and other types of agreements with suppliers.', 'preventive'),
  ('GV.SC-06', 'GV Govern', 'Planning and Due Diligence', 'Planning and due diligence are performed to reduce risks before entering into formal supplier or other third-party relationships.', 'preventive'),
  ('GV.SC-07', 'GV Govern', 'Supply Chain Controls', 'The risks posed by a supplier, their products and services and other third parties are identified, prioritized and addressed.', 'detective'),
  ('GV.SC-08', 'GV Govern', 'Supply Chain Incident Response', 'Relevant suppliers and other third parties are included in incident planning, response and recovery activities.', 'corrective'),
  ('GV.SC-09', 'GV Govern', 'Supply Chain Monitoring', 'Supply chain security practices are integrated into cybersecurity and enterprise risk management programs.', 'detective'),
  ('GV.SC-10', 'GV Govern', 'Supply Chain Review', 'Cybersecurity supply chain risk management plans include provisions for activities that occur after the conclusion of a partnership or agreement.', 'preventive'),
  -- ID – Identify
  ('ID.AM-01', 'ID Identify', 'Hardware Inventory', 'Inventories of hardware managed by the organization are maintained.', 'preventive'),
  ('ID.AM-02', 'ID Identify', 'Software Inventory', 'Inventories of software, services and systems managed by the organization are maintained.', 'preventive'),
  ('ID.AM-03', 'ID Identify', 'Data Inventory', 'Representations of the organization network and communications are maintained.', 'preventive'),
  ('ID.AM-04', 'ID Identify', 'External Systems Inventory', 'Inventories of services provided by suppliers are maintained.', 'preventive'),
  ('ID.AM-05', 'ID Identify', 'Resource Prioritization', 'Assets are prioritized based on classification, criticality, resources and impact.', 'preventive'),
  ('ID.AM-07', 'ID Identify', 'Inventories of Data', 'Inventories of data and corresponding metadata for designated data are maintained.', 'preventive'),
  ('ID.AM-08', 'ID Identify', 'System Lifecycle', 'Systems, hardware, software, services and data are managed throughout their lifecycle.', 'preventive'),
  ('ID.RA-01', 'ID Identify', 'Vulnerability Identification', 'Vulnerabilities in assets are identified, validated and recorded.', 'detective'),
  ('ID.RA-02', 'ID Identify', 'Threat Intelligence', 'Cyber threat intelligence is received from information sharing forums and sources.', 'detective'),
  ('ID.RA-03', 'ID Identify', 'Threat Identification', 'Internal and external threats to the organization are identified and recorded.', 'detective'),
  ('ID.RA-04', 'ID Identify', 'Risk Assessment', 'Potential impacts and likelihoods of threats exploiting vulnerabilities are identified and recorded.', 'detective'),
  ('ID.RA-05', 'ID Identify', 'Risk Prioritization', 'Threats, vulnerabilities, likelihoods and impacts are used to understand inherent risk and inform risk response priorities.', 'detective'),
  ('ID.RA-06', 'ID Identify', 'Risk Response', 'Risk responses are chosen, prioritized, planned, tracked and communicated.', 'preventive'),
  ('ID.RA-07', 'ID Identify', 'Change Risk', 'Changes and exceptions are managed, assessed for risk impact, recorded and tracked.', 'preventive'),
  ('ID.RA-08', 'ID Identify', 'Vulnerability Disclosure', 'Processes for receiving, analysing and responding to vulnerability disclosures are established.', 'detective'),
  ('ID.RA-09', 'ID Identify', 'Hardware and Software Supply Chain', 'The authenticity and integrity of hardware and software are assessed prior to acquisition and use.', 'preventive'),
  ('ID.RA-10', 'ID Identify', 'Critical Supplier Risk', 'Critical suppliers are assessed prior to acquisition.', 'preventive'),
  ('ID.IM-01', 'ID Identify', 'Improvement Plans', 'Improvements are identified from evaluations.', 'corrective'),
  ('ID.IM-02', 'ID Identify', 'Incident Improvements', 'Improvements are identified from security tests and exercises.', 'corrective'),
  ('ID.IM-03', 'ID Identify', 'Communication Improvements', 'Improvements are identified from execution of operational processes, procedures and activities.', 'corrective'),
  ('ID.IM-04', 'ID Identify', 'Incident Communication', 'Incident response plans and other cybersecurity plans that affect operations are established, communicated, maintained and improved.', 'corrective'),
  -- PR – Protect
  ('PR.AA-01', 'PR Protect', 'Identity Management', 'Identities and credentials for authorized users, services and hardware are managed by the organization.', 'preventive'),
  ('PR.AA-02', 'PR Protect', 'Remote Access', 'Identities are proofed and bound to credentials based on the context of interactions.', 'preventive'),
  ('PR.AA-03', 'PR Protect', 'User Authentication', 'Users, services and hardware are authenticated.', 'preventive'),
  ('PR.AA-04', 'PR Protect', 'Identity Assertions', 'Identity assertions are protected, conveyed and verified.', 'preventive'),
  ('PR.AA-05', 'PR Protect', 'Access Permissions', 'Access permissions, entitlements and authorizations are defined in a policy, managed, enforced and reviewed.', 'preventive'),
  ('PR.AA-06', 'PR Protect', 'Physical Access', 'Physical access to assets is managed, monitored and enforced commensurate with risk.', 'preventive'),
  ('PR.AT-01', 'PR Protect', 'Awareness Training', 'Personnel are provided with awareness and training so that they possess the knowledge and skills to perform their cybersecurity-related tasks.', 'preventive'),
  ('PR.AT-02', 'PR Protect', 'Privileged Role Training', 'Individuals in specialized roles are provided with awareness and training so they possess the knowledge and skills to perform relevant cybersecurity tasks.', 'preventive'),
  ('PR.DS-01', 'PR Protect', 'Data at Rest', 'The confidentiality, integrity and availability of data-at-rest are protected.', 'preventive'),
  ('PR.DS-02', 'PR Protect', 'Data in Transit', 'The confidentiality, integrity and availability of data-in-transit are protected.', 'preventive'),
  ('PR.DS-10', 'PR Protect', 'Data in Use', 'The confidentiality, integrity and availability of data-in-use are protected.', 'preventive'),
  ('PR.DS-11', 'PR Protect', 'Data Backups', 'Backups of data are created, protected, maintained and tested.', 'corrective'),
  ('PR.IR-01', 'PR Protect', 'Network Integrity', 'Networks and environments are protected from unauthorized logical access and usage.', 'preventive'),
  ('PR.IR-02', 'PR Protect', 'Vulnerable Environment Isolation', 'The organization network is protected from being discovered and targeted by adversaries.', 'preventive'),
  ('PR.IR-03', 'PR Protect', 'Remote Access Management', 'Remote access and external system connections are managed.', 'preventive'),
  ('PR.IR-04', 'PR Protect', 'Network Segmentation', 'Adequate resource capacity to ensure availability is maintained.', 'preventive'),
  ('PR.PS-01', 'PR Protect', 'Configuration Management', 'Configuration management practices are established and applied.', 'preventive'),
  ('PR.PS-02', 'PR Protect', 'Software Maintenance', 'Software is maintained, replaced and removed commensurate with risk.', 'preventive'),
  ('PR.PS-03', 'PR Protect', 'Hardware Maintenance', 'Hardware is maintained, replaced and removed commensurate with risk.', 'preventive'),
  ('PR.PS-04', 'PR Protect', 'Log Generation', 'Logs and security information are generated and made available for continuous monitoring.', 'detective'),
  ('PR.PS-05', 'PR Protect', 'Secure Installation', 'Installation and execution of unauthorized software are prevented.', 'preventive'),
  ('PR.PS-06', 'PR Protect', 'Secure Development', 'Secure software development practices are integrated and their performance is monitored throughout the software development lifecycle.', 'preventive'),
  -- DE – Detect
  ('DE.CM-01', 'DE Detect', 'Network Monitoring', 'Networks and network services are monitored to find potentially adverse events.', 'detective'),
  ('DE.CM-02', 'DE Detect', 'Physical Environment Monitoring', 'The physical environment is monitored to find potentially adverse events.', 'detective'),
  ('DE.CM-03', 'DE Detect', 'Personnel Activity Monitoring', 'Personnel activity and technology usage are monitored to find potentially adverse events.', 'detective'),
  ('DE.CM-06', 'DE Detect', 'External Service Activity Monitoring', 'External service provider activities and services are monitored to find potentially adverse events.', 'detective'),
  ('DE.CM-09', 'DE Detect', 'Computing Hardware Monitoring', 'Computing hardware and software, runtime environments and their data are monitored to find potentially adverse events.', 'detective'),
  ('DE.AE-02', 'DE Detect', 'Adverse Event Analysis', 'Potentially adverse events are analysed to better understand associated activities.', 'detective'),
  ('DE.AE-03', 'DE Detect', 'Event Data Correlation', 'Information is correlated from multiple sources.', 'detective'),
  ('DE.AE-04', 'DE Detect', 'Incident Impact Estimation', 'The estimated impact and scope of adverse events are understood.', 'detective'),
  ('DE.AE-06', 'DE Detect', 'Incident Reporting', 'A plan is in place to communicate security anomalies and events to appropriate parties.', 'detective'),
  ('DE.AE-07', 'DE Detect', 'Cyber Intelligence', 'Cyber threat intelligence and other contextual information are integrated into the analysis.', 'detective'),
  ('DE.AE-08', 'DE Detect', 'Incident Declaration', 'Incidents are declared when adverse events meet the defined incident criteria.', 'detective'),
  -- RS – Respond
  ('RS.MA-01', 'RS Respond', 'Incident Execution', 'The incident response plan is executed in coordination with relevant third parties once an incident is declared.', 'corrective'),
  ('RS.MA-02', 'RS Respond', 'Incident Triage', 'Incident reports are triaged to understand their impact, scope and severity in order to determine the appropriate response.', 'corrective'),
  ('RS.MA-03', 'RS Respond', 'Incident Categorization', 'Incidents are categorized and prioritized.', 'corrective'),
  ('RS.MA-04', 'RS Respond', 'Incident Escalation', 'Incidents are escalated or elevated as needed.', 'corrective'),
  ('RS.MA-05', 'RS Respond', 'Criteria for Escalation', 'Criteria for initiating incident recovery are applied.', 'corrective'),
  ('RS.AN-03', 'RS Respond', 'Root Cause Analysis', 'Analysis is performed to establish what has taken place during an incident and the root cause of the incident.', 'corrective'),
  ('RS.AN-06', 'RS Respond', 'Actions Documentation', 'Actions taken during an investigation are recorded to preserve the integrity of evidence and support the recovery of affected assets.', 'corrective'),
  ('RS.AN-07', 'RS Respond', 'Incident Containment', 'Cyber threat intelligence and other contextual information are integrated into the incident response activities.', 'corrective'),
  ('RS.AN-08', 'RS Respond', 'Scope Estimation', 'Incidents are categorized consistent with response plans.', 'corrective'),
  ('RS.CO-02', 'RS Respond', 'Internal Notification', 'Internal and external stakeholders are notified of incidents.', 'corrective'),
  ('RS.CO-03', 'RS Respond', 'External Coordination', 'Information is shared with designated internal and external authorities.', 'corrective'),
  ('RS.MI-01', 'RS Respond', 'Incident Containment', 'Incidents are contained.', 'corrective'),
  ('RS.MI-02', 'RS Respond', 'Incident Eradication', 'Incidents are eradicated.', 'corrective'),
  -- RC – Recover
  ('RC.RP-01', 'RC Recover', 'Recovery Plan Execution', 'The recovery portion of the incident response plan is executed once initiated from the incident response process.', 'corrective'),
  ('RC.RP-02', 'RC Recover', 'Recovery Planning', 'Recovery actions are selected, scoped, prioritized and performed.', 'corrective'),
  ('RC.RP-03', 'RC Recover', 'Recovery Verification', 'The integrity of backups and other restoration assets is verified before using them for restoration.', 'corrective'),
  ('RC.RP-04', 'RC Recover', 'Critical Services Restoration', 'Critical mission functions and cybersecurity capabilities are re-established.', 'corrective'),
  ('RC.RP-05', 'RC Recover', 'Full Services Restoration', 'The integrity of restored assets is verified, systems and services are restored, and normal operating status is confirmed.', 'corrective'),
  ('RC.RP-06', 'RC Recover', 'Closure Report', 'The end of incident recovery is declared based on criteria, and incident-related documentation is completed.', 'corrective'),
  ('RC.CO-03', 'RC Recover', 'Recovery Communication', 'Recovery activities and progress in restoring operational capabilities are communicated to designated internal and external stakeholders.', 'corrective'),
  ('RC.CO-04', 'RC Recover', 'Lessons Learned', 'Public updates on incident recovery are shared using approved methods and messaging.', 'corrective')
) AS c(control_id, domain, title, description, type)
ON CONFLICT (organization_id, framework, control_id) DO NOTHING;

-- ============================================================
-- Automatically populate Statement of Applicability for ISO 27001
-- ============================================================
INSERT INTO statement_of_applicability (organization_id, control_id, applicable, implementation_status)
SELECT
  fc.organization_id,
  fc.id,
  true,
  'not_started'
FROM framework_controls fc
WHERE fc.organization_id = :org_id
  AND fc.framework = 'ISO27001'
ON CONFLICT DO NOTHING;
